  # R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
  
  language: R
  sudo: false
  cache:
  packages: true
  
  script:
  - Rscript -e 'bookdown::render_book()'
  
  deploy:
  provider: pages
  local_dir: _book
  skip_cleanup: true
  keep-history: true
  github_token: $stat545_GITHUB_PAT
  target_branch: gh-pages